@startuml
title Authentication

participant Alice
participant Server

Alice -> Server: auth(name)
activate Server
alt success
    Alice <-- Server: SUCCESS
    Alice <<- Server: gameList(gameID1, gameID2, ...)
else player already exists
    Alice <-- Server: NAME_ALREADY_EXISTS
end
deactivate Server

@enduml