@startuml
title Create game and join

participant Alice
participant Bob
participant Carlos
participant Server

Alice -> Server: createGameAndJoin(maxPlayers)
activate Server
Alice <-- Server: gameCreated(gameID)
Alice <-- Server: GAME_JOINED
Alice <-- Server: playerList(player1, player2, ...)
note right: always empty (he is the first player that joined)
Alice <-- Server: gameCreated(gameID)

Bob -> Server: joinGame(gameID)
alt success
    Bob <-- Server: GAME_JOINED
    Bob <-- Server: playerList(player1, player2, ...)
else gameID doesn't exist
    Bob <-- Server: GAME_NOT_FOUND
end

Carlos -> Server: joinGame(gameID)
alt success
    Carlos <-- Server: GAME_JOINED
    Carlos <-- Server: playerList(player1, player2, ...)
else gameID doesn't exist
    Carlos <-- Server: GAME_NOT_FOUND
end
deactivate Server



@enduml