@startuml
!startsub PARTS
!include events.puml

!procedure $drawCard_req($client, $server=Server)
    $client -> $server: drawCard(drawSource)
!endprocedure

!procedure $drawCard_res_OK($client, $server=Server)
    $server --> $client: OK
!endprocedure

!endsub

title Draw a card
participant Alice
participant Server
participant Bob

hnote over Alice : IN_GAME
/ hnote over Bob : IN_GAME

note over Alice : It is Alice's turn

$event_seq_newTurn_DRAWING($inGame="Alice~Bob")

|||

$drawCard_req(Alice)
alt
    $drawCard_res_OK(Alice)
    $event_seq_updateDecksStatus("Alice~Bob")
    opt player has drawn a face up card
        $event_seq_updateFaceUpCards("Alice~Bob")
    end

    opt currentPlayer is the last player and someone reached an ending condition
        $event_seq_newStatus(LAST_TURN, "Alice~Bob")
    end
    $event_seq_newTurn_PLACING("Alice~Bob")
    note over Bob : It's Bob's turn
else source is empty
    Server --> Alice: KO, emptySource()
end


@enduml
