@startuml

'single events

!procedure $event_updateGameList($client, $server=Server)
    $client <<- $server: updateGameList(gameData1, gameData2, ...)
!endprocedure

!procedure $event_updatePlayerList($client, $server=Server)
    $client <<- $server: updatePlayerList(player1, player2, ...)
!endprocedure

!procedure $event_updateGameStatus($status, $client, $server=Server)
    $client <<- $server: updateGameStatus(<font:monospace><b>$status</b></font>)
!endprocedure

!procedure $event_updateTurn($turnPhase, $client, $sender=currentPlayer, $server=Server)
    $client <<- $server: updateTurn($sender, <font:monospace><b>$turnPhase</b></font>)
!endprocedure

!procedure $event_updateFaceUpCards($client, $server=Server)
    $client <<- $server: updateFaceUpCards(card1, card2, card3, card4)
!endprocedure

!procedure $event_updatePlayArea($client, $sender=currentPlayer, $server=Server)
    $client <<- $server: updatePlayArea($sender, cardPlacement)
!endprocedure

!procedure $event_setStartingCard($client, $server=Server)
    $client <<- $server: setStartingCard(startingCard)
!endprocedure

!procedure $event_setPlayablePosition($client, $server=Server)
    $client <<- $server: setPlayablePosition(position1, position2, ...)
!endprocedure

!procedure $event_updateFinalScores($client, $server=Server)
    $client <<- $server: updateFinalScores(playerScore1, playerScore2, ...)
!endprocedure

!procedure $event_updateMailbox($client, $MessageType, $server=Server)
    $client <<- $server: updateMailbox(sender, <font:monospace><b>$MessageType</b></font>, content)
!endprocedure

!procedure $event_updateScores($client, $sender=currentPlayer, $server=Server)
    $client <<- $server: updateScores($sender, score)
!endprocedure


'sequences

!procedure event_seq_newStatus($status, $inGame="")
    !foreach $c in %splitstr($inGame, "~")
        $event_updateGameStatus($status, $c)
    !endfor
!endprocedure

!procedure event_seq_newTurn($turnPhase, $inGame="", $sender)
    !foreach $c in %splitstr($inGame, "~")
        $event_updateTurn($turnPhase, $c, $sender)
    !endfor
!endprocedure

!procedure event_seq_newStatus_SETUP_STARTING_CARD_SIDE($inGame="", $server=Server)
    !foreach $c in %splitstr($inGame, "~")
        $c <<- $server: updateGameStatus(<font:monospace><b>SETUP_STARTING_CARD_SIDE</b></font>, startingCard)
    !endfor
!endprocedure

!procedure event_seq_newStatus_PLAY($status, $turnPhase, $inGame="", $server=Server)
    !foreach $c in %splitstr($inGame, "~")
        $c <<- $server: updateGameStatus(<font:monospace><b>$status</b></font>, <font:monospace><b>$turnPhase</b></font>, currentPlayer)
    !endfor
!endprocedure

!procedure event_seq_newStatus_SETUP_COLOR($inGame="")
    $event_seq_newStatus(SETUP_COLOR, $inGame)
!endprocedure

!procedure event_seq_newStatus_SETUP_OBJECTIVE($inGame="", $server=Server)
    !foreach $c in %splitstr($inGame, "~")
        $c <<- $server: updateGameStatus(<font:monospace><b>SETUP_OBJECTIVE</b></font>, objective1, objective2)
    !endfor
!endprocedure

!procedure event_seq_newTurn_PLACING($inGame="", $sender=currentPlayer)
    $event_seq_newTurn(PLACING, $inGame, $sender)
!endprocedure

!procedure event_seq_newTurn_DRAWING($inGame="", $sender=currentPlayer)
    $event_seq_newTurn(DRAWING, $inGame, $sender)
!endprocedure

!procedure event_seq_updatePlayArea($inGame="", $sender=currentPlayer)
    !foreach $c in %splitstr($inGame, "~")
        $event_updatePlayArea($c, $sender)
    !endfor
!endprocedure

!procedure event_seq_updateColor($inGame="")
    !foreach $c in %splitstr($inGame, "~")
       $event_updateColor($c)
    !endfor
!endprocedure

!procedure event_seq_setCommonObjectives($inGame="")
    !foreach $c in %splitstr($inGame, "~")
       $event_setCommonObjectives($c)
    !endfor
!endprocedure

!procedure event_seq_setCardsInHand($inGame="")
    !foreach $c in %splitstr($inGame, "~")
        $event_setCardsInHand($c)
    !endfor
!endprocedure

!procedure event_seq_updateFaceUpCards($inGame="")
    !foreach $c in %splitstr($inGame, "~")
        $event_updateFaceUpCards($c)
    !endfor
!endprocedure

!procedure event_seq_updateScores($inGame="", $sender=currentPlayer)
    !foreach $c in %splitstr($inGame, "~")
        $event_updateScores($c, $sender)
    !endfor
!endprocedure

!procedure event_seq_updateFinalScores($inGame="")
    !foreach $c in %splitstr($inGame, "~")
        $event_updateFinalScores($c)
    !endfor
!endprocedure

!procedure event_seq_updateMailboxes($inGame="")
    !foreach $c in %splitstr($inGame, "~")
        $event_updateMailbox($c, BROADCAST)
    !endfor
!endprocedure

!procedure event_seq_setBoard($inGame="", $server=Server)
    !foreach $client in %splitstr($inGame, "~")
        $client <<- $server: setBoard(commonObjective1, commonObjective2, faceUpCard1, faceUpCard2, faceUpCard3, faceUpCard4)
    !endfor
!endprocedure

!procedure event_seq_setHand($inGame="", $server=Server)
    !foreach $client in %splitstr($inGame, "~")
        $client <<- $server: setHand(card1, card2, card3, card4)
    !endfor
!endprocedure

!procedure event_seq_newStatus_FINISHED($inGame="", $server=Server)
    !foreach $client in %splitstr($inGame, "~")
        $client <<- $server: updateGameStatus(<font:monospace><b>FINISHED</b></font>, playerScore1, playerScore2, ...)
    !endfor
!endprocedure

@enduml
