@startuml
!startsub PARTS
!include events.puml
!endsub

title Game is finished
participant Alice
participant Server
participant Bob

hnote over Alice : IN_GAME
/ hnote over Bob : IN_GAME

note over Alice : Game has placed a card
$event_seq_newStatus(FINISHED, "Alice~Bob")
note over Alice : Game has finished
$event_seq_updateFinalScores("Alice~Bob")
'TODO: do we also send the winners, or are they calculated by the client?

hnote over Alice : AUTHENTICATED
/ hnote over Bob : AUTHENTICATED
@enduml