@startuml

' for all pages
!include events.puml

!procedure notifyStatusAll($status, $clients)
    !foreach $c in %splitstr($clients, "~")
        $event_updateGameStatus($status, NULL, $c)
    !endfor
!endprocedure

'first page
!includesub auth_detail.puml!PARTS

participant Alice
participant Bob
participant Carlos
participant Server

title User authentication
hnote over Alice : NOT_AUTHENTICATED
/ hnote over Bob : NOT_AUTHENTICATED
/ hnote over Carlos : NOT_AUTHENTICATED

$auth_seq_OK(Alice)
||25||
$auth_seq_OK(Bob)
||25||
$auth_seq_OK(Carlos)

newpage Create game and join
!includesub createGame_detail.puml!PARTS
!includesub joinGame_detail.puml!PARTS

$createGame_seq_OK(Alice, "Bob~Carlos")
||25||
$joinGame_seq_OK(Bob, "Carlos", "Alice~Bob")
||25||
$joinGame_seq_OK(Carlos, "", "Alice~Bob~Carlos")

newpage Game setup
!includesub selectStartingCardSide_detail.puml!PARTS
!includesub selectPlayerColor_detail.puml!PARTS
!includesub selectSecretObjective_detail.puml!PARTS

||75||

event_seq_newStatus_SETUP_STARTING_CARD_SIDE("Alice~Bob~Carlos")

||25||
$selectSide_seq("Alice", "Alice~Bob~Carlos")
||25||
$selectSide_seq("Bob", "Alice~Bob~Carlos")
||25||
$selectSide_seq("Carlos", "Alice~Bob~Carlos")

||75||

event_seq_newStatus_SETUP_COLOR("Alice~Bob~Carlos")

||75||

$selectColor_seq(Alice, "Alice~Bob~Carlos")
||25||
$selectColor_seq(Bob, "Alice~Bob~Carlos")
||25||
$selectColor_seq(Carlos, "Alice~Bob~Carlos")

||75||

event_seq_newStatus_SETUP_OBJECTIVE("Alice~Bob~Carlos")

||75||

$selectObjective_seq(Alice, "Alice~Bob~Carlos")
||25||
$selectObjective_seq(Bob, "Alice~Bob~Carlos")
||25||
$selectObjective_seq(Carlos, "Alice~Bob~Carlos")

@enduml
