@startuml

!startsub PARTS
!include events.puml

!procedure $selectSide_req($client, $server=Server)
    $client ->> $server: selectSide(side)
!endprocedure

!procedure $selectSide_res_OK($inGame="", $server=Server)
    !foreach $client in %splitstr($inGame, "~")
        $client <<- $server: updateSideChosenList(player1HasChosen, player2HasChosen, ...)
    !endfor
!endprocedure

!procedure $selectSide_res_seq_OK($client, $inGame="", $server=Server)
    $selectSide_req($client)
    $selectSide_res_OK($inGame)
    $event_seq_updatePlayArea($inGame, $client)
!endprocedure

!endsub

title Select starting card side
participant Alice
participant Server
participant Bob

hnote over Alice : IN_GAME
/ hnote over Bob : IN_GAME

event_seq_newStatus_SETUP_STARTING_CARD_SIDE($inGame="Alice~Bob", $server=Server)

|||

$selectSide_req(Alice)
alt
    $selectSide_res_OK("Alice~Bob")
    $event_seq_updatePlayArea("Alice~Bob", Alice)
    opt all players have selected a side
        event_seq_newStatus_SETUP_COLOR("Alice~Bob")
    end
else this player has already chosen the starting card side
    Alice <<- Server: KO, sideAlreadyChosen()
else the selected side is not a valid option
    Alice <<- Server: KO, invalidSide()
end

@enduml
