@startuml

!startsub PARTS
!include events.puml

!procedure $selectObjective_req($client, $server=Server)
    $client ->> $server: selectObjective(objective)
!endprocedure

!procedure $selectObjective_res_OK($inGame="", $server=Server)
    !foreach $client in %splitstr($inGame, "~")
        $client <<- $server: updateChosenObjectiveList(player1HasChosen, player2HasChosen, ...)
    !endfor
!endprocedure

!procedure $selectObjective_res_seq_OK($client, $inGame="", $server=Server)
    $selectObjective_req($client)
    $selectObjective_res_OK($inGame)
!endprocedure

!endsub

title Select secret objective
participant Alice
participant Server
participant Bob

hnote over Alice : IN_GAME
/ hnote over Bob : IN_GAME

event_seq_newStatus_SETUP_OBJECTIVE("Alice~Bob")

|||

$selectObjective_req(Alice)
alt 
    $selectObjective_res_OK("Alice~Bob")
    opt all players have selected secret objective
        event_seq_newStatusAndTurn($status=PLAY,$turnPhase=PLACING, $inGame="Alice~Bob")
        event_seq_setBoard("Alice~Bob")
        event_seq_setHand("Alice~Bob")
    end

else player has already chosen
    Alice <<- Server: KO, doubleChoice()
else invalid objective
    Alice <<- Server: KO, invalidObjective()
end

@enduml
